"""Repository interfaces: one per store, in-memory and MongoDB behind each.

Documents are plain JSON-safe dicts. All methods are async so routers await
one uniform convention; time fields are unix floats (converted to native
dates at the MongoDB boundary for TTL indexes).
"""
from __future__ import annotations

import hashlib
from typing import Protocol


def dedupe_key(user_id: str, jd: str, url: str, days: int) -> str:
    norm = lambda s: " ".join(str(s or "").lower().split())
    return hashlib.sha256(f"{user_id}|{norm(jd)}|{norm(url)}|{days}".encode()).hexdigest()


class Users(Protocol):
    async def create(self, email: str, pw_hash: str) -> dict: ...
    async def by_id(self, user_id: str) -> dict | None: ...
    async def by_email(self, email: str) -> dict | None: ...


class Sessions(Protocol):
    async def create(self, digest: str, user_id: str, expires_at: float) -> None: ...
    async def get(self, digest: str) -> dict | None: ...
    async def delete(self, digest: str) -> None: ...
    async def purge_expired(self, now: float) -> int: ...


class Kits(Protocol):
    async def create(self, doc: dict) -> None: ...
    async def get(self, kit_id: str) -> dict | None: ...
    async def list_for_user(self, user_id: str) -> list[dict]: ...
    async def save(self, doc: dict) -> None: ...
    async def delete(self, kit_id: str) -> None: ...
    async def find_by_dedupe(self, user_id: str, dedupe: str, statuses: tuple[str, ...]) -> dict | None: ...
    async def count_for_user(self, user_id: str) -> int: ...
    async def created_since(self, user_id: str, since_ts: float) -> int: ...


class Jobs(Protocol):
    async def create(self, doc: dict) -> None: ...
    async def create_active(self, doc: dict) -> None:
        """Create, enforcing one active (pending|running) job per Kit. Raises ConflictError."""
        ...
    async def get(self, job_id: str) -> dict | None: ...
    async def list_for_kit(self, kit_id: str) -> list[dict]: ...
    async def active_for_kit(self, kit_id: str) -> dict | None: ...
    async def running_count(self) -> int: ...
    async def running_for_user(self, user_id: str) -> int: ...
    async def claim_next(self, exclude: tuple[str, ...] = ()) -> dict | None:
        """Atomically move the oldest pending job to running. Returns it or None."""
        ...
    async def stale_running(self, before_ts: float) -> list[dict]: ...
    async def save(self, doc: dict) -> None: ...
    async def delete(self, job_id: str) -> None: ...
    async def delete_for_kit(self, kit_id: str) -> None: ...


class Practice(Protocol):
    async def reviews(self, key: str) -> list[dict]: ...
    async def append_review(self, key: str, review: dict) -> None: ...
    async def delete_for_kit(self, kit_id: str) -> None: ...


class PageCacheRepo(Protocol):
    async def get(self, url: str) -> dict | None: ...
    async def put(self, url: str, page: dict) -> None: ...
    async def purge_expired(self, now: float) -> int: ...


class Throttles(Protocol):
    async def get_times(self, key: str) -> list[float]: ...
    async def set_times(self, key: str, times: list[float]) -> None: ...


class Store(Protocol):
    users: Users
    sessions: Sessions
    kits: Kits
    jobs: Jobs
    practice: Practice
    page_cache: PageCacheRepo
    throttles: Throttles

    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...
    @property
    def durable(self) -> bool: ...
